---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-prometheus-alertmanager
  namespace: kubernetes-monitoring
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy.org/auth-type: basic-auth
    haproxy.org/auth-secret: monitoring-prometheus
    haproxy.org/path-rewrite: /prometheus-alert(/|$)(.*) /\2
spec:
  rules:
  - http:
      paths:
      - path: /prometheus-alert
        pathType: Prefix
        backend:
          service:
            name: monitoring-prometheus-alertmanager
            port:
              number: 80
