apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  allInOne:
    options:
      query:
        base-path: /jaeger
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy.org/auth-type: basic-auth
    haproxy.org/auth-secret: observability-jaeger
