apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-k8dash
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: haproxy
    ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
  - http:
      paths:
      - path: /kubernetes-dashboard
        pathType: Prefix
        backend:
          service:
            name: kubernetes-k8dash
            port:
              number: 80
