apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: hello-open-liberty
  namespace: open-liberty
spec:
  applicationImage: openliberty/open-liberty:full-java8-openj9-ubi
  service:
    type: ClusterIP
    port: 9080
  expose: true
  route:
    path: /
    pathType: Prefix
  statefulSet:
    storage:
      size: 2Gi
      mountPath: "/logs"
