apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-skooner
  namespace: kubernetes-skooner
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /kubernetes-dashboard
        pathType: Prefix
        backend:
          service:
            name: kubernetes-skooner
            port:
              number: 80
