---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-prometheus-alertmanager
  namespace: kubernetes-monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: monitoring-prometheus
spec:
  rules:
  - http:
      paths:
      - path: /prometheus-alert
        pathType: Prefix
        backend:
          service:
            name: monitoring-prometheus-alertmanager
            port:
              number: 80
