check.k8s.env.actions: false
ingress.controller: nginx
id: kubernetes
jaegerAction: addon-jaeger
monitoringAction: addon-monitoring
helm.version: v3.9.4
cni.plugins.version: 1.1.1
k9s.version: 0.26.7
crictl.version: v1.25.0
stern.version: 1.22.0
containerd.version: 1.4.13
ingress.nginx.version: 1.5.1
kubernetes.dashboard.version: 2.7.0
metallb.version: 0.13.7